# Generated by Django 2.2.1 on 2019-05-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='description_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='duty',
            name='description_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shool',
            name='endTitle_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shool',
            name='endTitle_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shool',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shool',
            name='name_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='name_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='project_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='project_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='company_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='company_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='position_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='position_pl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
